### ISSUE TITLE
Install issue - quickstart.sh does not unpack product data correctly

### ISSUE THREAD

**Issue by markharwood** [querqy/chorus-elasticsearch-edition#9]
* Clean install of MacOS Monterey.
* Ran brew install jq dependency

My shell scripting skills are minimal but this section looked to be trying to reformat the raw product data into an elasticsearch bulk file using `jq`. The issue was all the formatted output looked to be being dumped to the console rather than creating the file `transformed_data.json`

```
if [ ! -f ./transformed_data.json ]; then
  output=transformed_data.json

  for row in $(cat icecat-products-w_price-19k-20201127.json | jq -r '.[] | @base64'); do
      my_line=$(echo ${row} | base64 --decode)
      _id() {
       echo ${my_line} | jq -r .id
      }
      _jq() {
       echo ${my_line} | jq -r ${1}
      }
     echo { \"index\" : {\"_id\" : \"$(_id)\"}}
     echo $(_jq '.')
  done
fi
```

The subsequent bulk load command to elasticsearch obviously failed as a result of the missing file

**Comment by epugh** [comment]
Thanks @markharwood for the great feedback....    Please try out the latest, and if you have any other input/ideas, please holler.

**Comment by markharwood** [comment]
Great stuff. Thanks for the quick fix!
